name: cloud_firestore_rest
description: A new Flutter project.
version: 0.0.2
author: Anuar Otynshin
homepage: https://github.com/strigePC/firebase_rest

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  firebase_core: ^1.4.0

  json_annotation: ^4.0.0
  quiver: ^3.0.1
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1
  json_serializable: ^4.1.3
flutter: