name: cloud_firestore_rest
description: A new Flutter project.
version: 0.0.1
author: Anuar Otynshin
homepage: https://github.com/strigePC/firebase_rest

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.0
  firebase_core: ^1.0.0

  json_annotation: ^4.0.0
  quiver: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  json_serializable: ^4.0.2
flutter: